version: '3.0'

services:

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    command:
      - ganache-cli
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug
    networks:
      - diffuse-net

  diffuse:
    container_name: diffuse
    ports:
      - "3000:3000"
    build:
      context: '.'
      dockerfile: Dockerfile-dev
    restart: always
    networks:
      - diffuse-net
    depends_on:
      - ganache
    volumes:
      - ./:/usr/src/app

networks:
  diffuse-net:
    driver: bridge